name: CD | Publish Python ğŸ distributions ğŸ“¦ to PyPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  actions: write
  issues: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: python
          package-name: runpod

  build-n-publish:
    name: Build and publish Python ğŸ distributions ğŸ“¦ to PyPI
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: read
      id-token: write  # Required for OIDC

    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: Set up Python 3.11.10
        run: uv python install 3.11.10

      - name: Build package
        run: uv build

      - name: Publish distribution ğŸ“¦ to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/

      - name: Publish distribution ğŸ“¦ to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  notify-runpod-workers:
    name: Notify workers
    needs: [release-please, build-n-publish]
    if: ${{ needs.release-please.outputs.release_created }}
    strategy:
      matrix:
        repo:
          [
            "runpod-workers/worker-faster_whisper",
            "runpod-workers/worker-stable_diffusion_v1",
            "runpod-workers/worker-kandinsky",
            "runpod-workers/worker-stable_diffusion_v2",
            "runpod-workers/worker-template",
            "runpod-workers/worker-whisper",
            "runpod-workers/worker-esrgan",
            "runpod-workers/worker-github_runner",
            "runpod-workers/worker-a1111",
            "runpod-workers/worker-dreambooth",
            "runpod-workers/worker-bark",
            "runpod-workers/worker-gpt",
            "runpod-workers/worker-iseven",
            "runpod-workers/worker-controlnet",
            "runpod-workers/worker-blip",
            "runpod-workers/worker-deforum",
            runpod-workers/mock-worker,
          ]

    runs-on: ubuntu-latest

    steps:
      - name: Wait for propagation
        run: sleep 300s
        shell: bash

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.RUNPOD_WORKERS_PAT }}
          repository: ${{ matrix.repo }}
          event-type: python-package-release
